#service.elk:
#   container_name: service.elk
#   image: michaloo/elasticsearch
#   ports:
#       - "9200:9200"

#service.fluentd:
#    container_name: service.fluentd
#    build: dockerimages/service.fluentd/
#    ports:
#    - "24224:24224"
#    links:
#        - "service.elk:service-elk"


#service.kibana:
#    container_name: service.kibana
#    image: kibana
#    links:
#        - "service.elk:elasticsearch"
#    ports:
#        - "5601:5601"

service.auth:
  container_name: service.auth
  build: ./service.auth
  ports:
   - "57000:57000"
#  log_driver: fluentd

service.localstorexattr.prop.mysql:
  container_name: service.localstorexattr.prop.mysql
  image: mysql
  ports:
      - "3306:3306"
  environment:
    MYSQL_DATABASE: prop
    MYSQL_USER: prop
    MYSQL_PASSWORD: passforuserprop
    MYSQL_ROOT_PASSWORD: admin
#  log_driver: fluentd

service.localstorexattr.prop:
  container_name: service.localstorexattr.prop
  build: ./service.localstorexattr.prop
  ports:
   - "57003:57003"
  links:
   - "service.localstorexattr.prop.mysql:service-localstorexattr-prop-mysql"
#  log_driver: fluentd

service.localstorexattr.data:
  container_name: service.localstorexattr.data
  build: ./service.localstorexattr.data
  ports:
   - "57002:57002"
  volumes:
   - /tmp:/tmp
  links:
   - "service.localstorexattr.prop:service-localstorexattr-prop"
#  log_driver: fluentd

service.localstorexattr.meta:
  container_name: service.localstorexattr.meta
  build: ./service.localstorexattr.meta
  ports:
   - "57001:57001"
  volumes:
   - /tmp:/tmp
  links:
   - "service.localstorexattr.prop:service-localstorexattr-prop"
#  log_driver: fluentd

service.ocwebdav:
  container_name: service.ocwebdav
  build: ./service.ocwebdav
  ports:
      - "57004:57004"
  links:
      - "service.localstorexattr.data:service-localstorexattr-data"
      - "service.localstorexattr.meta:service-localstorexattr-meta"
      - "service.auth:service-auth"
  environment:
    CLAWIO_OCWEBDAV_META: "service-localstorexattr-meta:57001"
    CLAWIO_OCWEBDAV_DATA: "http://service-localstorexattr-data:57002"
#  log_driver: fluentd
