#!/usr/bin/bash

# In production you really want to change this variable 
CLAWIO_INSTALL_PATH=/tmp/clawioproject

mkdir -p ${CLAWIO_INSTALL_PATH}
cd ${CLAWIO_INSTALL_PATH}

# Clone required services. Add your own.
git clone https://github.com/clawio/orches
git clone https://github.com/clawio/service.auth
git clone https://github.com/clawio/service.localstore.data
git clone https://github.com/clawio/service.localstore.meta
git clone https://github.com/clawio/service.ocwebdav
git clone https://github.com/clawio/service.localstore.prop

cp orches/docker-compose.yml .

# Ideally docker-compose up -d will be enough but given that
# some containers need to be launched in sequence and 
# compose does not guarantee that, we launch them in manually
# in the desired sequence.
docker-compose up -d --force-recreate service.auth
docker-compose up -d service.auth

docker-compose up -d --force-recreate service.localstore.prop.mysql
docker-compose up -d service.localstore.prop.mysql

docker-compose up -d --force-recreate service.localstore.prop
docker-compose up -d service.localstore.prop

docker-compose up -d --force-recreate service.localstore.meta
docker-compose up -d service.localstore.meta

docker-compose up -d --force-recreate service.localstore.data
docker-compose up -d service.localstore.data

docker-compose up -d --force-recreate service.ocwebdav
docker-compose up -d service.ocwebdav

# Being paranoic ...
docker-compose up -d
docker-compose up -d
docker-compose up -d

# Show running containers. All should have state Up
docker-compose ps
